export const BASE = 'https://data.surinametijdmachine.org/';
export const WD = 'http://www.wikidata.org/entity/';

/** Context used by compact, self-contained authority-record JSON-LD documents. */
export function buildPlaceRecordContext(): Record<string, unknown> {
  return {
    ...buildContext(),
    stm: BASE,
    AuthorityRecord: 'stm:AuthorityRecord',
    E31_Document: 'crm:E31_Document',
    E42_Identifier: 'crm:E42_Identifier',
    E99_Product_Type: 'crm:E99_Product_Type',
    E17_Type_Assignment: 'crm:E17_Type_Assignment',
    describes: { '@id': 'stm:describes', '@type': '@id' },
    hasOrganizationalAssociation: {
      '@id': 'stm:hasOrganizationalAssociation',
      '@type': '@id',
    },
    associatedPhysicalPlantation: {
      '@id': 'stm:associatedPhysicalPlantation',
      '@type': '@id',
    },
    certainty: { '@id': 'stm:certainty', '@type': '@id' },
    reportedOperationalStatus: {
      '@id': 'stm:reportedOperationalStatus',
      '@type': '@id',
    },
    sourcePath: { '@id': 'stm:sourcePath', '@type': 'xsd:string' },
    sourceRow: { '@id': 'stm:sourceRow', '@type': 'xsd:string' },
    sourceUrl: { '@id': 'sdo:url', '@type': '@id' },
    standardizedContent: {
      '@id': 'stm:standardizedContent',
      '@type': 'xsd:string',
    },
    sranantongoName: {
      '@id': 'stm:sranantongoName',
      '@type': 'xsd:string',
    },
    reportedComponentOrganization: {
      '@id': 'stm:reportedComponentOrganization',
      '@type': '@id',
    },
    reportedComponentOrganizationLabel: {
      '@id': 'stm:reportedComponentOrganizationLabel',
      '@type': 'xsd:string',
    },
    reportedCompositeOrganization: {
      '@id': 'stm:reportedCompositeOrganization',
      '@type': '@id',
    },
    reportedCompositeOrganizationLabel: {
      '@id': 'stm:reportedCompositeOrganizationLabel',
      '@type': 'xsd:string',
    },
    reportedOwnerOrganization: {
      '@id': 'stm:reportedOwnerOrganization',
      '@type': '@id',
    },
    reportedOwnerOrganizationLabel: {
      '@id': 'stm:reportedOwnerOrganizationLabel',
      '@type': 'xsd:string',
    },
    enslavedSharedWith: {
      '@id': 'stm:enslavedSharedWith',
      '@type': 'xsd:string',
    },
    sourceVersion: { '@id': 'stm:sourceVersion', '@type': 'xsd:string' },
    sourcePlantationQid: {
      '@id': 'stm:sourcePlantationQid',
      '@type': 'xsd:string',
    },
    standardizedName: { '@id': 'stm:standardizedName', '@type': 'xsd:string' },
    littera: { '@id': 'stm:littera', '@type': 'xsd:string' },
    districtOrDivision: {
      '@id': 'stm:districtOrDivision',
      '@type': 'xsd:string',
    },
    riverOrRoad: { '@id': 'stm:riverOrRoad', '@type': 'xsd:string' },
    direction: { '@id': 'stm:direction', '@type': 'xsd:string' },
    psurIds: { '@id': 'stm:psurIds', '@type': 'xsd:string' },
    referenceOriginal: {
      '@id': 'stm:referenceOriginal',
      '@type': 'xsd:string',
    },
    sizeAkkers: { '@id': 'stm:sizeAkkers', '@type': 'xsd:integer' },
    function: { '@id': 'stm:function', '@type': 'xsd:string' },
    additionalInfo: { '@id': 'stm:additionalInfo', '@type': 'xsd:string' },
    lot: { '@id': 'stm:lot', '@type': 'xsd:string' },
    population: { '@id': 'stm:population', '@type': '@json' },
    mill: { '@id': 'stm:mill', '@type': '@json' },
    rawManagement: { '@id': 'stm:rawManagement', '@type': '@json' },
    sourceContent: { '@id': 'stm:sourceContent', '@type': 'xsd:string' },
    P3_has_note: { '@id': 'crm:P3_has_note', '@type': 'xsd:string' },
    P41_classified: { '@id': 'crm:P41_classified', '@type': '@id' },
    P42_assigned: { '@id': 'crm:P42_assigned', '@type': '@id' },
    P48_has_preferred_identifier: {
      '@id': 'crm:P48_has_preferred_identifier',
      '@type': '@id',
    },
    P81a_end_of_the_begin: {
      '@id': 'crm:P81a_end_of_the_begin',
      '@type': 'xsd:gYear',
    },
    P81b_begin_of_the_end: {
      '@id': 'crm:P81b_begin_of_the_end',
      '@type': 'xsd:gYear',
    },
    P82a_begin_of_the_begin: {
      '@id': 'crm:P82a_begin_of_the_begin',
      '@type': 'xsd:gYear',
    },
    P82b_end_of_the_end: {
      '@id': 'crm:P82b_end_of_the_end',
      '@type': 'xsd:gYear',
    },
    P89_falls_within: { '@id': 'crm:P89_falls_within', '@type': '@id' },
    rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
  };
}

export function buildContext(): Record<string, unknown> {
  return {
    '@vocab': 'https://schema.org/',
    base: BASE,
    stm: BASE,
    wd: WD,
    wdt: 'http://www.wikidata.org/prop/direct/',
    crm: 'http://www.cidoc-crm.org/cidoc-crm/',
    geo: 'http://www.opengis.net/ont/geosparql#',
    skos: 'http://www.w3.org/2004/02/skos/core#',
    prov: 'http://www.w3.org/ns/prov#',
    sdo: 'https://schema.org/',
    xsd: 'http://www.w3.org/2001/XMLSchema#',
    dcterms: 'http://purl.org/dc/terms/',
    owl: 'http://www.w3.org/2002/07/owl#',
    oa: 'http://www.w3.org/ns/oa#',
    picom: 'https://personsincontext.org/model#',
    picot: 'https://personsincontext.org/thesaurus#',
    pnv: 'https://w3id.org/pnv#',
    rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
    rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
    hdsc: 'https://data.colonialheritage.nl/ontology/',
    ed: 'https://lod.enslaved.org/wiki/',

    id: '@id',
    type: '@type',
    _label: 'rdfs:label',
    AuthorityRecord: 'stm:AuthorityRecord',
    Place: 'crm:E53_Place',
    Name: 'crm:E41_Appellation',
    Identifier: 'crm:E42_Identifier',
    Type: 'crm:E55_Type',
    HumanMadeFeature: 'crm:E25_Human-Made_Feature',
    PhysicalFeature: 'crm:E26_Physical_Feature',
    Geometry: 'geo:Geometry',
    Group: 'crm:E74_Group',
    AttributeAssignment: 'crm:E13_Attribute_Assignment',
    TypeAssignment: 'crm:E17_Type_Assignment',
    TimeSpan: 'crm:E52_Time-Span',
    Concept: 'skos:Concept',
    ConceptScheme: 'skos:ConceptScheme',
    Plantation: 'crm:E25_Human-Made_Feature',
    OrganizationObservation: 'crm:E13_Attribute_Assignment',
    ProvenanceRecord: 'prov:Entity',
    E13_Attribute_Assignment: 'crm:E13_Attribute_Assignment',
    E22_Human_Made_Object: 'crm:E22_Human-Made_Object',
    'E22_Human-Made_Object': 'crm:E22_Human-Made_Object',
    E24_Physical_Human_Made_Thing: 'crm:E24_Physical_Human-Made_Thing',
    'E24_Physical_Human-Made_Thing': 'crm:E24_Physical_Human-Made_Thing',
    E25_Human_Made_Feature: 'crm:E25_Human-Made_Feature',
    'E25_Human-Made_Feature': 'crm:E25_Human-Made_Feature',
    E26_Physical_Feature: 'crm:E26_Physical_Feature',
    E36_Visual_Item: 'crm:E36_Visual_Item',
    E41_Appellation: 'crm:E41_Appellation',
    E52_Time_Span: 'crm:E52_Time-Span',
    'E52_Time-Span': 'crm:E52_Time-Span',
    E53_Place: 'crm:E53_Place',
    E55_Type: 'crm:E55_Type',
    E74_Group: 'crm:E74_Group',
    E12_Production: 'crm:E12_Production',
    PresenceInference: 'stm:PresenceInference',
    PlantationCompositionPeriod: 'stm:PlantationCompositionPeriod',
    InferenceRule: 'prov:Plan',
    OrganizationAuthorityOverride: 'stm:OrganizationAuthorityOverride',
    physicalLinkReviewStatus: 'stm:physicalLinkReviewStatus',
    reviewedPhysicalPlaceIds: 'stm:reviewedPhysicalPlaceId',
    associatedPhysicalPlaceIds: 'stm:associatedPhysicalPlaceId',
    functionEvidenceKind: 'stm:functionEvidenceKind',
    firstAttestedYear: 'stm:firstAttestedYear',
    lastAttestedYear: 'stm:lastAttestedYear',
    observationYears: 'stm:observationYear',
    hasEvidence: { '@id': 'stm:hasEvidence', '@type': '@id' },
    hasOperationalSummary: {
      '@id': 'stm:hasOperationalSummary',
      '@type': '@id',
    },
    hasFunctionSummary: {
      '@id': 'stm:hasFunctionSummary',
      '@type': '@id',
    },
    hasFunctionAssignment: {
      '@id': 'stm:hasFunctionAssignment',
      '@type': '@id',
    },

    P1_is_identified_by: { '@id': 'crm:P1_is_identified_by', '@type': '@id' },
    P1i_identifies: { '@id': 'crm:P1i_identifies', '@type': '@id' },
    P2_has_type: { '@id': 'crm:P2_has_type', '@type': '@id' },
    P4_has_time_span: { '@id': 'crm:P4_has_time-span', '@type': '@id' },
    'P4_has_time-span': { '@id': 'crm:P4_has_time-span', '@type': '@id' },
    P46_is_composed_of: {
      '@id': 'crm:P46_is_composed_of',
      '@type': '@id',
    },
    P46i_forms_part_of: {
      '@id': 'crm:P46i_forms_part_of',
      '@type': '@id',
    },
    P51_has_former_or_current_owner: {
      '@id': 'crm:P51_has_former_or_current_owner',
      '@type': '@id',
    },
    P52_has_current_owner: {
      '@id': 'crm:P52_has_current_owner',
      '@type': '@id',
    },
    P53_has_location: {
      '@id': 'crm:P53_has_former_or_current_location',
      '@type': '@id',
    },
    P53_has_former_or_current_location: {
      '@id': 'crm:P53_has_former_or_current_location',
      '@type': '@id',
    },
    P70i_is_documented_in: {
      '@id': 'crm:P70i_is_documented_in',
      '@type': '@id',
    },
    P72_has_language: { '@id': 'crm:P72_has_language', '@type': '@id' },
    P82a_begin_of_the_begin: {
      '@id': 'crm:P82a_begin_of_the_begin',
      '@type': 'xsd:gYear',
    },
    P82b_end_of_the_end: {
      '@id': 'crm:P82b_end_of_the_end',
      '@type': 'xsd:gYear',
    },
    P92i_was_brought_into_existence_by: {
      '@id': 'crm:P92i_was_brought_into_existence_by',
      '@type': '@id',
    },
    P93i_was_taken_out_of_existence_by: {
      '@id': 'crm:P93i_was_taken_out_of_existence_by',
      '@type': '@id',
    },
    P128_carries: { '@id': 'crm:P128_carries', '@type': '@id' },
    P128i_is_carried_by: { '@id': 'crm:P128i_is_carried_by', '@type': '@id' },
    P138_represents: { '@id': 'crm:P138_represents', '@type': '@id' },
    P138i_has_representation: {
      '@id': 'crm:P138i_has_representation',
      '@type': '@id',
    },
    P139_has_alternative_form: {
      '@id': 'crm:P139_has_alternative_form',
      '@type': '@id',
    },
    P140_assigned_attribute_to: {
      '@id': 'crm:P140_assigned_attribute_to',
      '@type': '@id',
    },
    P141_assigned: { '@id': 'crm:P141_assigned', '@type': '@id' },
    P7_took_place_at: { '@id': 'crm:P7_took_place_at', '@type': 'xsd:string' },
    P14_carried_out_by: {
      '@id': 'crm:P14_carried_out_by',
      '@type': 'xsd:string',
    },
    P108_has_produced: { '@id': 'crm:P108_has_produced', '@type': '@id' },
    P108i_was_produced_by: {
      '@id': 'crm:P108i_was_produced_by',
      '@type': '@id',
    },
    P50_has_current_keeper: {
      '@id': 'crm:P50_has_current_keeper',
      '@type': 'xsd:string',
    },
    contentUrl: { '@id': 'sdo:contentUrl', '@type': '@id' },
    P190_has_symbolic_content: {
      '@id': 'crm:P190_has_symbolic_content',
      '@type': 'xsd:string',
    },
    identified_by: { '@id': 'crm:P1_is_identified_by', '@type': '@id' },
    classified_as: { '@id': 'crm:P2_has_type', '@type': '@id' },
    content: 'crm:P190_has_symbolic_content',
    language: { '@id': 'crm:P72_has_language', '@type': '@id' },
    carried_by: { '@id': 'crm:P128i_is_carried_by', '@type': '@id' },
    documented_by: { '@id': 'crm:P70i_is_documented_in', '@type': '@id' },
    defined_by: {
      '@id': 'crm:P168_place_is_defined_by',
      '@type': 'geo:wktLiteral',
    },
    centroid: { '@id': 'geo:hasCentroid', '@type': '@id' },
    as_wkt: { '@id': 'geo:asWKT', '@type': 'geo:wktLiteral' },
    part_of: { '@id': 'crm:P89_falls_within', '@type': '@id' },
    related_features: {
      '@id': 'crm:P53i_is_former_or_current_location_of',
      '@type': '@id',
    },
    associated_organizations: {
      '@id': 'stm:hasOrganizationalAssociation',
      '@type': '@id',
    },
    organization_association_status: {
      '@id': 'stm:organizationAssociationStatus',
      '@type': 'xsd:string',
    },
    attributed_by: {
      '@id': 'crm:P140i_was_attributed_by',
      '@type': '@id',
    },
    classified_by: {
      '@id': 'crm:P41i_was_classified_by',
      '@type': '@id',
    },
    assigned_attribute: { '@id': 'crm:P141_assigned', '@type': '@id' },
    assigned_type: { '@id': 'crm:P42_assigned', '@type': '@id' },
    timespan: { '@id': 'crm:P4_has_time-span', '@type': '@id' },
    begin_of_the_begin: {
      '@id': 'crm:P82a_begin_of_the_begin',
      '@type': 'xsd:gYear',
    },
    end_of_the_end: {
      '@id': 'crm:P82b_end_of_the_end',
      '@type': 'xsd:gYear',
    },
    evidence: { '@id': 'prov:hadPrimarySource', '@type': '@id' },
    derived_from: { '@id': 'prov:wasDerivedFrom', '@type': '@id' },
    note: { '@id': 'crm:P3_has_note', '@type': 'xsd:string' },
    standardized_content: {
      '@id': 'stm:standardizedContent',
      '@type': 'xsd:string',
    },
    source_content: { '@id': 'stm:sourceContent', '@type': 'xsd:string' },
    source_row: { '@id': 'dcterms:identifier', '@type': 'xsd:string' },
    exact_match: { '@id': 'skos:exactMatch', '@type': '@id' },
    close_match: { '@id': 'skos:closeMatch', '@type': '@id' },
    broad_match: { '@id': 'skos:broadMatch', '@type': '@id' },
    narrow_match: { '@id': 'skos:narrowMatch', '@type': '@id' },
    related_match: { '@id': 'skos:relatedMatch', '@type': '@id' },

    prefLabel: 'skos:prefLabel',
    altLabel: 'skos:altLabel',
    definition: 'skos:definition',
    example: 'skos:example',
    hiddenLabel: 'skos:hiddenLabel',
    scopeNote: 'skos:scopeNote',
    historyNote: 'skos:historyNote',
    broader: { '@id': 'skos:broader', '@type': '@id' },
    narrower: { '@id': 'skos:narrower', '@type': '@id' },
    related: { '@id': 'skos:related', '@type': '@id' },
    inScheme: { '@id': 'skos:inScheme', '@type': '@id' },
    topConceptOf: { '@id': 'skos:topConceptOf', '@type': '@id' },
    hasTopConcept: { '@id': 'skos:hasTopConcept', '@type': '@id' },
    notation: 'skos:notation',
    closeMatch: { '@id': 'skos:closeMatch', '@type': '@id' },
    exactMatch: { '@id': 'skos:exactMatch', '@type': '@id' },
    broadMatch: { '@id': 'skos:broadMatch', '@type': '@id' },
    narrowMatch: { '@id': 'skos:narrowMatch', '@type': '@id' },
    relatedMatch: { '@id': 'skos:relatedMatch', '@type': '@id' },
    typeId: { '@id': 'stm:typeId', '@type': 'xsd:string' },
    color: { '@id': 'stm:color', '@type': 'xsd:string' },
    crmClass: { '@id': 'stm:crmClass', '@type': 'xsd:string' },
    crmBadge: { '@id': 'stm:crmBadge', '@type': 'xsd:string' },
    sortOrder: { '@id': 'stm:sortOrder', '@type': 'xsd:integer' },
    created: { '@id': 'dcterms:created', '@type': 'xsd:date' },
    modified: { '@id': 'dcterms:modified', '@type': 'xsd:date' },
    deprecated: { '@id': 'owl:deprecated', '@type': 'xsd:boolean' },
    deprecatedAt: {
      '@id': 'prov:invalidatedAtTime',
      '@type': 'xsd:date',
    },
    deprecatedBy: { '@id': 'stm:deprecatedBy', '@type': 'xsd:string' },
    replacedBy: { '@id': 'dcterms:isReplacedBy', '@type': '@id' },
    deprecationNote: {
      '@id': 'stm:deprecationNote',
      '@type': 'xsd:string',
    },
    hasOrganizationalAssociation: {
      '@id': 'stm:hasOrganizationalAssociation',
      '@type': '@id',
    },
    associatedPhysicalPlantation: {
      '@id': 'stm:associatedPhysicalPlantation',
      '@type': '@id',
    },
    hasDerivedInference: {
      '@id': 'stm:hasDerivedInference',
      '@type': '@id',
    },
    inferredPopulationAssociatedWith: {
      '@id': 'stm:inferredPopulationAssociatedWith',
      '@type': '@id',
    },
    inferredPresenceAt: { '@id': 'stm:inferredPresenceAt', '@type': '@id' },
    inferredPlace: { '@id': 'stm:inferredPlace', '@type': '@id' },
    populationCategory: { '@id': 'stm:populationCategory', '@type': '@id' },
    populationCount: { '@id': 'stm:populationCount', '@type': 'xsd:integer' },
    certainty: { '@id': 'stm:certainty', '@type': '@id' },
    inferenceRule: { '@id': 'stm:inferenceRule', '@type': '@id' },
    presenceInferenceStatus: {
      '@id': 'stm:presenceInferenceStatus',
      '@type': 'xsd:string',
    },
    editorialNote: { '@id': 'dcterms:description', '@type': 'xsd:string' },
    authorityReviewStatus: {
      '@id': 'stm:authorityReviewStatus',
      '@type': 'xsd:string',
    },
    organizationAssociationStatus: {
      '@id': 'stm:organizationAssociationStatus',
      '@type': 'xsd:string',
    },
    modifiedAt: { '@id': 'dcterms:modified', '@type': 'xsd:date' },
    modifiedBy: { '@id': 'stm:modifiedBy', '@type': 'xsd:string' },
    hasGeometry: 'geo:hasGeometry',
    asWKT: { '@id': 'geo:asWKT', '@type': 'geo:wktLiteral' },
    additionalType: { '@id': 'sdo:additionalType', '@type': '@id' },
    affiliation: { '@id': 'sdo:affiliation', '@type': '@id' },
    parentOrganization: { '@id': 'sdo:parentOrganization', '@type': '@id' },
    subOrganization: { '@id': 'sdo:subOrganization', '@type': '@id' },
    sameAs: { '@id': 'sdo:sameAs', '@type': '@id' },
    'dcterms:description': {
      '@id': 'dcterms:description',
      '@type': 'xsd:string',
    },
    'dcterms:identifier': {
      '@id': 'dcterms:identifier',
      '@type': 'xsd:string',
    },
    'skos:broader': { '@id': 'skos:broader', '@type': '@id' },

    featureType: { '@id': 'stm:featureType', '@type': 'xsd:string' },
    mainBodyWater: { '@id': 'crm:P3_has_note', '@type': 'xsd:string' },
    status: { '@id': 'stm:status', '@type': 'xsd:string' },
    psurId: { '@id': 'stm:psurId', '@type': 'xsd:string' },
    fid: { '@id': 'stm:fid', '@type': 'xsd:integer' },
    mapId: { '@id': 'stm:mapId', '@type': 'xsd:string' },
    mapYear: { '@id': 'stm:mapYear', '@type': 'xsd:gYear' },
    observedLabel: { '@id': 'stm:observedLabel', '@type': 'xsd:string' },
    geometrySource: { '@id': 'prov:wasDerivedFrom', '@type': '@id' },
    absorbedInto: { '@id': 'crm:P99i_was_dissolved_by', '@type': '@id' },
    mergedInto: { '@id': 'crm:P124_transformed', '@type': '@id' },
    observationOf: { '@id': 'crm:P140_assigned_attribute_to', '@type': '@id' },
    observationYear: { '@id': 'stm:observationYear', '@type': 'xsd:gYear' },
    observedName: { '@id': 'stm:observedName', '@type': 'xsd:string' },
    product: { '@id': 'stm:productLabel', '@type': 'xsd:string' },
    enslavedCount: { '@id': 'stm:enslavedCount', '@type': 'xsd:integer' },
    privateEnslavedCount: {
      '@id': 'stm:privateEnslavedCount',
      '@type': 'xsd:integer',
    },
    explicitPlantationEnslavedCount: {
      '@id': 'stm:explicitPlantationEnslavedCount',
      '@type': 'xsd:integer',
    },
    deserted: { '@id': 'stm:desertedReported', '@type': 'xsd:boolean' },
    freeResidentsCount: {
      '@id': 'stm:freeResidentsCount',
      '@type': 'xsd:integer',
    },
    hasOwner: { '@id': 'stm:ownerTranscription', '@type': 'xsd:string' },
    hasAdministrator: {
      '@id': 'stm:administratorTranscription',
      '@type': 'xsd:string',
    },
    hasDirector: { '@id': 'stm:directorTranscription', '@type': 'xsd:string' },
    locationStd: { '@id': 'stm:locationLabel', '@type': 'xsd:string' },
    sizeAkkers: { '@id': 'stm:sizeAkkers', '@type': 'xsd:integer' },
    pageReference: { '@id': 'crm:P3_has_note', '@type': 'xsd:string' },
    depictedOnMap: { '@id': 'crm:P138i_has_representation' },
    labelOnMap: {
      '@id': 'crm:P190_has_symbolic_content',
      '@type': 'xsd:string',
    },
    hasPolygon: { '@id': 'geo:sfContains', '@type': 'xsd:boolean' },
    isEnslavedBy: { '@id': 'hdsc:isEnslavedBy', '@type': '@id' },
    isEnslaverOf: { '@id': 'hdsc:isEnslaverOf', '@type': '@id' },

    wasDerivedFrom: { '@id': 'prov:wasDerivedFrom', '@type': '@id' },
    hadPrimarySource: { '@id': 'prov:hadPrimarySource', '@type': '@id' },
    generatedAtTime: { '@id': 'prov:generatedAtTime', '@type': 'xsd:dateTime' },
    sourceFile: { '@id': 'stm:sourceFile', '@type': 'xsd:string' },
    sourceColumn: { '@id': 'dcterms:description', '@type': 'xsd:string' },
    sourceRow: { '@id': 'dcterms:identifier', '@type': 'xsd:string' },
    transformedBy: { '@id': 'stm:transformedBy', '@type': 'xsd:string' },
    modelEntity: { '@id': 'dcterms:conformsTo', '@type': 'xsd:string' },
    schemaTable: { '@id': 'dcterms:isPartOf', '@type': 'xsd:string' },
    linkedVia: { '@id': 'rdfs:comment', '@type': 'xsd:string' },
    sourceMaker: { '@id': 'stm:sourceMaker', '@type': 'xsd:string' },
    publicationPlace: { '@id': 'stm:publicationPlace', '@type': 'xsd:string' },
    holdingArchive: { '@id': 'stm:holdingArchive', '@type': 'xsd:string' },
    sranantongoName: {
      '@id': 'stm:sranantongoName',
      '@type': 'xsd:string',
    },
    reportedComponentOrganization: {
      '@id': 'stm:reportedComponentOrganization',
      '@type': '@id',
    },
    reportedComponentOrganizationLabel: {
      '@id': 'stm:reportedComponentOrganizationLabel',
      '@type': 'xsd:string',
    },
    reportedCompositeOrganization: {
      '@id': 'stm:reportedCompositeOrganization',
      '@type': '@id',
    },
    reportedCompositeOrganizationLabel: {
      '@id': 'stm:reportedCompositeOrganizationLabel',
      '@type': 'xsd:string',
    },
    reportedOwnerOrganization: {
      '@id': 'stm:reportedOwnerOrganization',
      '@type': '@id',
    },
    reportedOwnerOrganizationLabel: {
      '@id': 'stm:reportedOwnerOrganizationLabel',
      '@type': 'xsd:string',
    },
    enslavedSharedWith: {
      '@id': 'stm:enslavedSharedWith',
      '@type': 'xsd:string',
    },
    sourcePlantationQid: {
      '@id': 'stm:sourcePlantationQid',
      '@type': 'xsd:string',
    },
  };
}

export function buildContextDocument(): { '@context': Record<string, unknown> } {
  return { '@context': buildContext() };
}
