// Copies data/nas-mediabank/nas-mediabank-records.json into app/lib/ so the
// Next.js file tracer (which forbids globs that escape the project root) can
// bundle it into the event API serverless functions. The destination is
// gitignored and regenerated by `pnpm pipeline`, so changes in the source
// file flow through to deployments without a separate commit.
import { copyFileSync, existsSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, '..', '..', 'data', 'nas-mediabank', 'nas-mediabank-records.json');
const target = join(here, '..', 'lib', 'nas-mediabank-records.json');

if (!existsSync(source)) {
  throw new Error(`Missing NAS records file: ${source}. Run \`pnpm harvest-nas-mediabank\` first.`);
}

mkdirSync(dirname(target), { recursive: true });
copyFileSync(source, target);
console.log(`Synced NAS records to ${target}`);
